// Report type definitions matching the Python script
export const REPORT_TYPES = {
  BALANCE_SHEET: "zcfzb", // 资产负债表
  INCOME_STATEMENT: "lrb", // 利润表
  CASH_FLOW: "xjllb", // 现金流量表
} as const

export type ReportType = (typeof REPORT_TYPES)[keyof typeof REPORT_TYPES]

export const REPORT_TYPE_LABELS: Record<ReportType, string> = {
  [REPORT_TYPES.BALANCE_SHEET]: "资产负债表",
  [REPORT_TYPES.INCOME_STATEMENT]: "利润表",
  [REPORT_TYPES.CASH_FLOW]: "现金流量表",
}

// Report item definitions with hierarchy levels (from Python script)
export interface ReportItem {
  name: string
  level: number
}

export const BALANCE_SHEET_ITEMS: ReportItem[] = [
  // 流动资产
  { name: "流动资产:", level: 0 },
  { name: "货币资金", level: 1 },
  { name: "结算备付金", level: 1 },
  { name: "拆出资金", level: 1 },
  { name: "交易性金融资产", level: 1 },
  { name: "衍生金融资产", level: 1 },
  { name: "应收票据", level: 1 },
  { name: "应收账款", level: 1 },
  { name: "应收款项融资", level: 1 },
  { name: "预付款项", level: 1 },
  { name: "应收保费", level: 1 },
  { name: "应收分保账款", level: 1 },
  { name: "应收分保合同准备金", level: 1 },
  { name: "其他应收款", level: 1 },
  { name: "应收利息", level: 2 },
  { name: "应收股利", level: 2 },
  { name: "买入返售金融资产", level: 1 },
  { name: "存货", level: 1 },
  { name: "合同资产", level: 1 },
  { name: "持有待售资产", level: 1 },
  { name: "一年内到期的非流动资产", level: 1 },
  { name: "其他流动资产", level: 1 },
  { name: "流动资产合计", level: 0 },
  // 非流动资产
  { name: "非流动资产:", level: 0 },
  { name: "发放贷款和垫款", level: 1 },
  { name: "债权投资", level: 1 },
  { name: "其他债权投资", level: 1 },
  { name: "长期应收款", level: 1 },
  { name: "长期股权投资", level: 1 },
  { name: "其他权益工具投资", level: 1 },
  { name: "其他非流动金融资产", level: 1 },
  { name: "投资性房地产", level: 1 },
  { name: "固定资产", level: 1 },
  { name: "在建工程", level: 1 },
  { name: "生产性生物资产", level: 1 },
  { name: "油气资产", level: 1 },
  { name: "使用权资产", level: 1 },
  { name: "无形资产", level: 1 },
  { name: "开发支出", level: 1 },
  { name: "商誉", level: 1 },
  { name: "长期待摊费用", level: 1 },
  { name: "递延所得税资产", level: 1 },
  { name: "其他非流动资产", level: 1 },
  { name: "非流动资产合计", level: 0 },
  { name: "资产总计", level: 0 },
  // 流动负债
  { name: "流动负债:", level: 0 },
  { name: "短期借款", level: 1 },
  { name: "向中央银行借款", level: 1 },
  { name: "拆入资金", level: 1 },
  { name: "交易性金融负债", level: 1 },
  { name: "衍生金融负债", level: 1 },
  { name: "应付票据", level: 1 },
  { name: "应付账款", level: 1 },
  { name: "预收款项", level: 1 },
  { name: "合同负债", level: 1 },
  { name: "卖出回购金融资产款", level: 1 },
  { name: "吸收存款及同业存放", level: 1 },
  { name: "代理买卖证券款", level: 1 },
  { name: "代理承销证券款", level: 1 },
  { name: "应付职工薪酬", level: 1 },
  { name: "应交税费", level: 1 },
  { name: "其他应付款", level: 1 },
  { name: "应付利息", level: 2 },
  { name: "应付股利", level: 2 },
  { name: "应付手续费及佣金", level: 1 },
  { name: "应付分保账款", level: 1 },
  { name: "持有待售负债", level: 1 },
  { name: "一年内到期的非流动负债", level: 1 },
  { name: "其他流动负债", level: 1 },
  { name: "流动负债合计", level: 0 },
  // 非流动负债
  { name: "非流动负债:", level: 0 },
  { name: "保险合同准备金", level: 1 },
  { name: "长期借款", level: 1 },
  { name: "应付债券", level: 1 },
  { name: "优先股", level: 2 },
  { name: "永续债", level: 2 },
  { name: "租赁负债", level: 1 },
  { name: "长期应付款", level: 1 },
  { name: "长期应付职工薪酬", level: 1 },
  { name: "预计负债", level: 1 },
  { name: "递延收益", level: 1 },
  { name: "递延所得税负债", level: 1 },
  { name: "其他非流动负债", level: 1 },
  { name: "非流动负债合计", level: 0 },
  { name: "负债合计", level: 0 },
  // 所有者权益
  { name: "所有者权益(或股东权益):", level: 0 },
  { name: "实收资本(或股本)", level: 1 },
  { name: "其他权益工具", level: 1 },
  { name: "优先股", level: 2 },
  { name: "永续债", level: 2 },
  { name: "资本公积", level: 1 },
  { name: "减:库存股", level: 1 },
  { name: "其他综合收益", level: 1 },
  { name: "专项储备", level: 1 },
  { name: "盈余公积", level: 1 },
  { name: "一般风险准备", level: 1 },
  { name: "未分配利润", level: 1 },
  { name: "归属于母公司所有者权益合计", level: 0 },
  { name: "少数股东权益", level: 1 },
  { name: "所有者权益合计", level: 0 },
  { name: "负债和所有者权益总计", level: 0 },
]

export const INCOME_STATEMENT_ITEMS: ReportItem[] = [
  { name: "一、营业总收入", level: 0 },
  { name: "营业收入", level: 1 },
  { name: "利息收入", level: 1 },
  { name: "已赚保费", level: 1 },
  { name: "手续费及佣金收入", level: 1 },
  { name: "二、营业总成本", level: 0 },
  { name: "营业成本", level: 1 },
  { name: "利息支出", level: 1 },
  { name: "手续费及佣金支出", level: 1 },
  { name: "退保金", level: 1 },
  { name: "赔付支出净额", level: 1 },
  { name: "提取保险责任准备金净额", level: 1 },
  { name: "保单红利支出", level: 1 },
  { name: "分保费用", level: 1 },
  { name: "税金及附加", level: 1 },
  { name: "销售费用", level: 1 },
  { name: "管理费用", level: 1 },
  { name: "研发费用", level: 1 },
  { name: "财务费用", level: 1 },
  { name: "利息费用", level: 2 },
  { name: "利息收入", level: 2 },
  { name: "加:其他收益", level: 0 },
  { name: "投资收益", level: 1 },
  { name: "其中:对联营企业和合营企业的投资收益", level: 2 },
  { name: "以摊余成本计量的金融资产终止确认收益", level: 2 },
  { name: "汇兑收益", level: 1 },
  { name: "净敞口套期收益", level: 1 },
  { name: "公允价值变动收益", level: 1 },
  { name: "信用减值损失", level: 1 },
  { name: "资产减值损失", level: 1 },
  { name: "资产处置收益", level: 1 },
  { name: "三、营业利润", level: 0 },
  { name: "加:营业外收入", level: 1 },
  { name: "减:营业外支出", level: 1 },
  { name: "四、利润总额", level: 0 },
  { name: "减:所得税费用", level: 1 },
  { name: "五、净利润", level: 0 },
  { name: "(一)按经营持续性分类:", level: 1 },
  { name: "1.持续经营净利润", level: 2 },
  { name: "2.终止经营净利润", level: 2 },
  { name: "(二)按所有权归属分类:", level: 1 },
  { name: "1.归属于母公司所有者的净利润", level: 2 },
  { name: "2.少数股东损益", level: 2 },
  { name: "六、其他综合收益的税后净额", level: 0 },
  { name: "(一)归属母公司所有者的其他综合收益的税后净额", level: 1 },
  { name: "1.不能重分类进损益的其他综合收益", level: 2 },
  { name: "(1)重新计量设定受益计划变动额", level: 3 },
  { name: "(2)权益法下不能转损益的其他综合收益", level: 3 },
  { name: "(3)其他权益工具投资公允价值变动", level: 3 },
  { name: "(4)企业自身信用风险公允价值变动", level: 3 },
  { name: "2.将重分类进损益的其他综合收益", level: 2 },
  { name: "(1)权益法下可转损益的其他综合收益", level: 3 },
  { name: "(2)其他债权投资公允价值变动", level: 3 },
  { name: "(3)金融资产重分类计入其他综合收益的金额", level: 3 },
  { name: "(4)其他债权投资信用减值准备", level: 3 },
  { name: "(5)现金流量套期储备", level: 3 },
  { name: "(6)外币财务报表折算差额", level: 3 },
  { name: "(二)归属于少数股东的其他综合收益的税后净额", level: 1 },
  { name: "七、综合收益总额", level: 0 },
  { name: "(一)归属于母公司所有者的综合收益总额", level: 1 },
  { name: "(二)归属于少数股东的综合收益总额", level: 1 },
  { name: "八、每股收益:", level: 0 },
  { name: "(一)基本每股收益", level: 1 },
  { name: "(二)稀释每股收益", level: 1 },
]

export const CASH_FLOW_ITEMS: ReportItem[] = [
  { name: "一、经营活动产生的现金流量:", level: 0 },
  { name: "销售商品、提供劳务收到的现金", level: 1 },
  { name: "客户存款和同业存放款项净增加额", level: 1 },
  { name: "向中央银行借款净增加额", level: 1 },
  { name: "向其他金融机构拆入资金净增加额", level: 1 },
  { name: "收到原保险合同保费取得的现金", level: 1 },
  { name: "收到再保险业务现金净额", level: 1 },
  { name: "保户储金及投资款净增加额", level: 1 },
  { name: "收取利息、手续费及佣金的现金", level: 1 },
  { name: "拆入资金净增加额", level: 1 },
  { name: "回购业务资金净增加额", level: 1 },
  { name: "代理买卖证券收到的现金净额", level: 1 },
  { name: "收到的税费返还", level: 1 },
  { name: "收到其他与经营活动有关的现金", level: 1 },
  { name: "经营活动现金流入小计", level: 0 },
  { name: "购买商品、接受劳务支付的现金", level: 1 },
  { name: "客户贷款及垫款净增加额", level: 1 },
  { name: "存放中央银行和同业款项净增加额", level: 1 },
  { name: "支付原保险合同赔付款项的现金", level: 1 },
  { name: "拆出资金净增加额", level: 1 },
  { name: "支付利息、手续费及佣金的现金", level: 1 },
  { name: "支付保单红利的现金", level: 1 },
  { name: "支付给职工以及为职工支付的现金", level: 1 },
  { name: "支付的各项税费", level: 1 },
  { name: "支付其他与经营活动有关的现金", level: 1 },
  { name: "经营活动现金流出小计", level: 0 },
  { name: "经营活动产生的现金流量净额", level: 0 },
  { name: "二、投资活动产生的现金流量:", level: 0 },
  { name: "收回投资收到的现金", level: 1 },
  { name: "取得投资收益收到的现金", level: 1 },
  { name: "处置固定资产、无形资产和其他长期资产收回的现金净额", level: 1 },
  { name: "处置子公司及其他营业单位收到的现金净额", level: 1 },
  { name: "收到其他与投资活动有关的现金", level: 1 },
  { name: "投资活动现金流入小计", level: 0 },
  { name: "购建固定资产、无形资产和其他长期资产支付的现金", level: 1 },
  { name: "投资支付的现金", level: 1 },
  { name: "质押贷款净增加额", level: 1 },
  { name: "取得子公司及其他营业单位支付的现金净额", level: 1 },
  { name: "支付其他与投资活动有关的现金", level: 1 },
  { name: "投资活动现金流出小计", level: 0 },
  { name: "投资活动产生的现金流量净额", level: 0 },
  { name: "三、筹资活动产生的现金流量:", level: 0 },
  { name: "吸收投资收到的现金", level: 1 },
  { name: "其中:子公司吸收少数股东投资收到的现金", level: 2 },
  { name: "取得借款收到的现金", level: 1 },
  { name: "收到其他与筹资活动有关的现金", level: 1 },
  { name: "筹资活动现金流入小计", level: 0 },
  { name: "偿还债务支付的现金", level: 1 },
  { name: "分配股利、利润或偿付利息支付的现金", level: 1 },
  { name: "其中:子公司支付给少数股东的股利、利润", level: 2 },
  { name: "支付其他与筹资活动有关的现金", level: 1 },
  { name: "筹资活动现金流出小计", level: 0 },
  { name: "筹资活动产生的现金流量净额", level: 0 },
  { name: "四、汇率变动对现金及现金等价物的影响", level: 0 },
  { name: "五、现金及现金等价物净增加额", level: 0 },
  { name: "加:期初现金及现金等价物余额", level: 1 },
  { name: "六、期末现金及现金等价物余额", level: 0 },
]

export const REPORT_ITEMS: Record<ReportType, ReportItem[]> = {
  [REPORT_TYPES.BALANCE_SHEET]: BALANCE_SHEET_ITEMS,
  [REPORT_TYPES.INCOME_STATEMENT]: INCOME_STATEMENT_ITEMS,
  [REPORT_TYPES.CASH_FLOW]: CASH_FLOW_ITEMS,
}

// API field mappings for each report type
export const FIELD_MAPPINGS: Record<ReportType, Record<string, string>> = {
  [REPORT_TYPES.BALANCE_SHEET]: {
    货币资金: "MONETARYFUNDS",
    结算备付金: "SETTLE_RESERVES",
    拆出资金: "LEND_FUND",
    交易性金融资产: "TRADE_FINASSET_NOTFVTPL",
    衍生金融资产: "DERIVE_FINASSET",
    应收票据: "NOTE_RECEIVE",
    应收账款: "ACCOUNTS_RECE",
    应收款项融资: "FINANCE_RECE",
    预付款项: "PREPAYMENT",
    应收保费: "PREMIUM_RECE",
    应收分保账款: "REINSURE_RECE",
    应收分保合同准备金: "RC_RESERVE_RECE",
    其他应收款: "OTHER_RECE_SUM",
    应收利息: "INTEREST_RECE",
    应收股利: "DIVIDEND_RECE",
    买入返售金融资产: "BUY_RESALE_FINASSET",
    存货: "INVENTORY",
    合同资产: "CONTRACT_ASSET",
    持有待售资产: "HOLDSALE_ASSET",
    一年内到期的非流动资产: "NONCURRENT_ASSET_1Y",
    其他流动资产: "OTHER_CURRENT_ASSET",
    流动资产合计: "TOTAL_CURRENT_ASSETS",
    发放贷款和垫款: "LOAN_ADVANCE",
    债权投资: "CREDITOR_INVEST",
    其他债权投资: "OTHER_CREDITOR_INVEST",
    长期应收款: "LONG_RECE",
    长期股权投资: "LONG_EQUITY_INVEST",
    其他权益工具投资: "OTHER_EQUITY_INVEST",
    其他非流动金融资产: "OTHER_NONCURRENT_FINASSET",
    投资性房地产: "INVEST_REALESTATE",
    固定资产: "FIXED_ASSET",
    在建工程: "CIP",
    生产性生物资产: "PRODUCTIVE_BIOLOGY_ASSET",
    油气资产: "OIL_GAS_ASSET",
    使用权资产: "USERIGHT_ASSET",
    无形资产: "INTANGIBLE_ASSET",
    开发支出: "DEVELOP_EXPENSE",
    商誉: "GOODWILL",
    长期待摊费用: "LONG_PREPAID_EXPENSE",
    递延所得税资产: "DEFER_TAX_ASSET",
    其他非流动资产: "OTHER_NONCURRENT_ASSET",
    非流动资产合计: "TOTAL_NONCURRENT_ASSETS",
    资产总计: "TOTAL_ASSETS",
    短期借款: "SHORT_LOAN",
    向中央银行借款: "BORROW_CENTRAL_BANK",
    拆入资金: "BORROW_FUND",
    交易性金融负债: "TRADE_FINLIAB_NOTFVTPL",
    衍生金融负债: "DERIVE_FINLIAB",
    应付票据: "NOTE_PAYABLE",
    应付账款: "ACCOUNTS_PAYABLE",
    预收款项: "ADVANCE_RECEIVABLES",
    合同负债: "CONTRACT_LIAB",
    卖出回购金融资产款: "SELL_REPO_FINASSET",
    吸收存款及同业存放: "ACCEPT_DEPOSIT_INTERBANK",
    代理买卖证券款: "AGENT_TRADE_SECURITY",
    代理承销证券款: "AGENT_UNDERWRITE_SECURITY",
    应付职工薪酬: "STAFF_SALARY_PAYABLE",
    应交税费: "TAX_PAYABLE",
    其他应付款: "OTHER_PAYABLE_SUM",
    应付利息: "INTEREST_PAYABLE",
    应付股利: "DIVIDEND_PAYABLE",
    应付手续费及佣金: "FEE_COMMISSION_PAYABLE",
    应付分保账款: "REINSURE_PAYABLE",
    持有待售负债: "HOLDSALE_LIAB",
    一年内到期的非流动负债: "NONCURRENT_LIAB_1Y",
    其他流动负债: "OTHER_CURRENT_LIAB",
    流动负债合计: "TOTAL_CURRENT_LIAB",
    保险合同准备金: "INSURANCE_CONTRACT_RESERVE",
    长期借款: "LONG_LOAN",
    应付债券: "BOND_PAYABLE",
    优先股: "PREFERRED_STOCK",
    永续债: "PERPETUAL_BOND",
    租赁负债: "LEASE_LIAB",
    长期应付款: "LONG_PAYABLE",
    长期应付职工薪酬: "LONG_STAFFSALARY_PAYABLE",
    预计负债: "PREDICT_LIAB",
    递延收益: "DEFER_INCOME",
    递延所得税负债: "DEFER_TAX_LIAB",
    其他非流动负债: "OTHER_NONCURRENT_LIAB",
    非流动负债合计: "TOTAL_NONCURRENT_LIAB",
    负债合计: "TOTAL_LIABILITIES",
    "实收资本(或股本)": "SHARE_CAPITAL",
    其他权益工具: "OTHER_EQUITY_TOOL",
    资本公积: "CAPITAL_RESERVE",
    "减:库存股": "TREASURY_STOCK",
    其他综合收益: "OTHER_COMPRE_INCOME",
    专项储备: "SPECIAL_RESERVE",
    盈余公积: "SURPLUS_RESERVE",
    一般风险准备: "GENERAL_RISK_RESERVE",
    未分配利润: "UNASSIGN_PROFIT",
    归属于母公司所有者权益合计: "TOTAL_PARENT_EQUITY",
    少数股东权益: "MINORITY_EQUITY",
    所有者权益合计: "TOTAL_EQUITY",
    负债和所有者权益总计: "TOTAL_LIAB_EQUITY",
  },
  [REPORT_TYPES.INCOME_STATEMENT]: {
    "一、营业总收入": "TOTAL_OPERATE_INCOME",
    营业收入: "OPERATE_INCOME",
    利息收入: "INTEREST_INCOME",
    已赚保费: "EARNED_PREMIUM",
    手续费及佣金收入: "FEE_COMMISSION_INCOME",
    "二、营业总成本": "TOTAL_OPERATE_COST",
    营业成本: "OPERATE_COST",
    利息支出: "INTEREST_EXPENSE",
    手续费及佣金支出: "FEE_COMMISSION_EXPENSE",
    退保金: "SURRENDER_VALUE",
    赔付支出净额: "NET_COMPENSATE_EXPENSE",
    提取保险责任准备金净额: "NET_CONTRACT_RESERVE",
    保单红利支出: "POLICY_BONUS_EXPENSE",
    分保费用: "REINSURE_EXPENSE",
    税金及附加: "OPERATE_TAX_ADD",
    销售费用: "SALE_EXPENSE",
    管理费用: "MANAGE_EXPENSE",
    研发费用: "RESEARCH_EXPENSE",
    财务费用: "FINANCE_EXPENSE",
    利息费用: "FE_INTEREST_EXPENSE",
    "加:其他收益": "OTHER_INCOME",
    投资收益: "INVEST_INCOME",
    "其中:对联营企业和合营企业的投资收益": "INVEST_JOINT_INCOME",
    以摊余成本计量的金融资产终止确认收益: "END_FINASSET_INCOME",
    汇兑收益: "EXCHANGE_INCOME",
    净敞口套期收益: "NET_EXPOSURE_INCOME",
    公允价值变动收益: "FAIRVALUE_CHANGE_INCOME",
    信用减值损失: "CREDIT_IMPAIRMENT_INCOME",
    资产减值损失: "ASSET_IMPAIRMENT_INCOME",
    资产处置收益: "ASSET_DISPOSAL_INCOME",
    "三、营业利润": "OPERATE_PROFIT",
    "加:营业外收入": "NONBUSINESS_INCOME",
    "减:营业外支出": "NONBUSINESS_EXPENSE",
    "四、利润总额": "TOTAL_PROFIT",
    "减:所得税费用": "INCOME_TAX",
    "五、净利润": "NETPROFIT",
    "(一)按经营持续性分类:": "",
    "1.持续经营净利润": "CONTINUED_NETPROFIT",
    "2.终止经营净利润": "DISCONTINUED_NETPROFIT",
    "(二)按所有权归属分类:": "",
    "1.归属于母公司所有者的净利润": "PARENT_NETPROFIT",
    "2.少数股东损益": "MINORITY_INTEREST",
    "六、其他综合收益的税后净额": "OTHER_COMPRE_INCOME",
    "(一)归属母公司所有者的其他综合收益的税后净额": "PARENT_OCI",
    "1.不能重分类进损益的其他综合收益": "UNABLE_OCI",
    "(1)重新计量设定受益计划变动额": "REMEASURE_BENEFIT_PLAN",
    "(2)权益法下不能转损益的其他综合收益": "EQUITY_UNABLE_OCI",
    "(3)其他权益工具投资公允价值变动": "OEI_FAIRVALUE_CHANGE",
    "(4)企业自身信用风险公允价值变动": "CREDIT_RISK_FAIRVALUE_CHANGE",
    "2.将重分类进损益的其他综合收益": "ABLE_OCI",
    "(1)权益法下可转损益的其他综合收益": "EQUITY_ABLE_OCI",
    "(2)其他债权投资公允价值变动": "ODI_FAIRVALUE_CHANGE",
    "(3)金融资产重分类计入其他综合收益的金额": "FINASSET_OCI_AMOUNT",
    "(4)其他债权投资信用减值准备": "ODI_IMPAIRMENT_RESERVE",
    "(5)现金流量套期储备": "CASHFLOW_HEDGE_RESERVE",
    "(6)外币财务报表折算差额": "FOREIGN_CURRENCY_CONVERT",
    "(二)归属于少数股东的其他综合收益的税后净额": "MINORITY_OCI",
    "七、综合收益总额": "TOTAL_COMPRE_INCOME",
    "(一)归属于母公司所有者的综合收益总额": "PARENT_TCI",
    "(二)归属于少数股东的综合收益总额": "MINORITY_TCI",
    "八、每股收益:": "",
    "(一)基本每股收益": "BASIC_EPS",
    "(二)稀释每股收益": "DILUTED_EPS",
  },
  [REPORT_TYPES.CASH_FLOW]: {
    "销售商品、提供劳务收到的现金": "SALES_SERVICES",
    客户存款和同业存放款项净增加额: "DEPOSIT_INTERBANK_ADD",
    向中央银行借款净增加额: "BORROW_CENTRAL_BANK_ADD",
    向其他金融机构拆入资金净增加额: "BORROW_OTHER_FI_ADD",
    收到原保险合同保费取得的现金: "RECEIVE_ORIGIC_PREMIUM",
    收到再保险业务现金净额: "RECEIVE_REINSURE_NET",
    保户储金及投资款净增加额: "INSURED_INVEST_ADD",
    "收取利息、手续费及佣金的现金": "RECEIVE_INTEREST_COMMISSION",
    拆入资金净增加额: "BORROW_FUND_ADD",
    回购业务资金净增加额: "LOAN_ADVANCE_REDUCE",
    代理买卖证券收到的现金净额: "AGENT_TRADE_SECURITY_NET",
    收到的税费返还: "RECEIVE_TAX_REFUND",
    收到其他与经营活动有关的现金: "RECEIVE_OTHER_OPERATE",
    经营活动现金流入小计: "TOTAL_OPERATE_INFLOW",
    "购买商品、接受劳务支付的现金": "BUY_SERVICES",
    客户贷款及垫款净增加额: "LOAN_ADVANCE_ADD",
    存放中央银行和同业款项净增加额: "PBC_INTERBANK_ADD",
    支付原保险合同赔付款项的现金: "PAY_ORIGIC_COMPENSATE",
    拆出资金净增加额: "LEND_FUND_ADD",
    "支付利息、手续费及佣金的现金": "PAY_INTEREST_COMMISSION",
    支付保单红利的现金: "PAY_POLICY_BONUS",
    支付给职工以及为职工支付的现金: "PAY_STAFF_CASH",
    支付的各项税费: "PAY_ALL_TAX",
    支付其他与经营活动有关的现金: "PAY_OTHER_OPERATE",
    经营活动现金流出小计: "TOTAL_OPERATE_OUTFLOW",
    经营活动产生的现金流量净额: "NETCASH_OPERATE",
    收回投资收到的现金: "WITHDRAW_INVEST",
    取得投资收益收到的现金: "RECEIVE_INVEST_INCOME",
    "处置固定资产、无形资产和其他长期资产收回的现金净额": "DISPOSAL_LONGASSET_NET",
    处置子公司及其他营业单位收到的现金净额: "DISPOSAL_SUBSIDIARY_NET",
    收到其他与投资活动有关的现金: "RECEIVE_OTHER_INVEST",
    投资活动现金流入小计: "TOTAL_INVEST_INFLOW",
    "购建固定资产、无形资产和其他长期资产支付的现金": "CONSTRUCT_LONGASSET_CASH",
    投资支付的现金: "INVEST_PAY_CASH",
    质押贷款净增加额: "PLEDGE_LOAN_ADD",
    取得子公司及其他营业单位支付的现金净额: "OBTAIN_SUBSIDIARY_NET",
    支付其他与投资活动有关的现金: "PAY_OTHER_INVEST",
    投资活动现金流出小计: "TOTAL_INVEST_OUTFLOW",
    投资活动产生的现金流量净额: "NETCASH_INVEST",
    吸收投资收到的现金: "ACCEPT_INVEST_CASH",
    "其中:子公司吸收少数股东投资收到的现金": "SUBSIDIARY_ACCEPT_INVEST",
    取得借款收到的现金: "RECEIVE_LOAN_CASH",
    收到其他与筹资活动有关的现金: "RECEIVE_OTHER_FINANCE",
    筹资活动现金流入小计: "TOTAL_FINANCE_INFLOW",
    偿还债务支付的现金: "PAY_DEBT_CASH",
    "分配股利、利润或偿付利息支付的现金": "PAY_INTEREST_DIVIDEND",
    "其中:子公司支付给少数股东的股利、利润": "SUBSIDIARY_PAY_DIVIDEND",
    支付其他与筹资活动有关的现金: "PAY_OTHER_FINANCE",
    筹资活动现金流出小计: "TOTAL_FINANCE_OUTFLOW",
    筹资活动产生的现金流量净额: "NETCASH_FINANCE",
    "四、汇率变动对现金及现金等价物的影响": "RATE_CHANGE_EFFECT",
    "五、现金及现金等价物净增加额": "CCE_ADD",
    "加:期初现金及现金等价物余额": "BEGIN_CCE",
    "六、期末现金及现金等价物余额": "END_CCE",
  },
}
